## __Proccessing batches__

Let's figure out how we can process batches of data. First let's look at our inputs and weights. 

$$
I = \begin{bmatrix}
1 & 2 & 3 & 4 \\
0.5 & 2.5 & -3.5 & -2 \\
\end{bmatrix}
$$

$$
W = \begin{bmatrix}
0.3 & -0.2 & 0.5 & 1.1 \\
-0.6 & 0.8 & 2.2 & 0.1 \\
0.5 & 0.9 & -0.7 & -3.1 \\
\end{bmatrix}
$$

Here, we can see see that our inputs are a 2x4 matrix, representing 2 samples in a batch, and are weights are a 4x3 matrix, representing 4 weights from input neurons, for 3 output neurons. Since dot product multiples by row and column, we need to first, __transpose__ the weights, or else there will an error.

In [1]:
import numpy as np

inputs = np.array([[1, 2, 3, 4], [0.5, 2.5, -3.5, -2]])

weights = np.array([[0.3, -0.2, 0.5, 1.1],
          [-0.6, 0.8, 2.2, 0.1],
          [0.5, 0.9, -0.7, -3.1]])

bias = np.array([-4, 2, 1])

print(weights.T)

[[ 0.3 -0.6  0.5]
 [-0.2  0.8  0.9]
 [ 0.5  2.2 -0.7]
 [ 1.1  0.1 -3.1]]


Here's what our weights look like now

$$
W_{t} = \begin{bmatrix}
0.3 & -0.6 & 0.5 \\
-0.2 & 0.8 & 0.9 \\
0.5 & 2.2 & -0.7 \\
1.1 & 0.1 & -3.1 \\
\end{bmatrix}
$$

We can see that the weights have been transposed, and now we can perform dot product.


In [2]:
import numpy as np

inputs = np.array([[1, 2, 3, 4], [0.5, 2.5, -3.5, -2]])

weights = np.array([[0.3, -0.2, 0.5, 1.1],
          [-0.6, 0.8, 2.2, 0.1],
          [0.5, 0.9, -0.7, -3.1]])

bias = np.array([-4, 2, 1])

output = np.dot(inputs, weights.T) + bias

print(output)

[[  1.8   10.   -11.2 ]
 [ -8.3   -4.2   12.15]]


Now let's take our implementation, and turn it into a class, for ease of use. We will create a Dense class, whose weights will be randomly initialized and biases set to zero. Then we create a method for our implementation. Now it's much easier to add multiple layers to our model. We can set the input neurons the same as the output neurons of the previous layer, and pass the output of the previous layer, as the input of the current layer.

In [3]:
class Dense:
  def __init__(self, input_neurons, output_neurons):
    self.weights = np.random.randn(input_neurons, output_neurons)
    self.biases = np.zeros((1, output_neurons))
  def forward(self, inputs):
    self.output = np.dot(inputs, self.weights) + self.biases

layer_one = Dense(4, 3)
layer_one.forward(inputs)
layer_two = Dense(3, 5)
layer_two.forward(layer_one.output)
print(layer_two.output)

[[  4.40853063   5.03445423   5.10404735  -1.0734144   -2.57989465]
 [  3.23757994 -16.50948996 -11.13038356  16.96942164  13.00812626]]


Now we have implemented a basic neural network with a 4-3-5 architecture, but there's a lot more to do! Let's now start adding activation functions into our neural network.